spring.application.name=g3_java
spring.datasource.url=jdbc:h2:mem:g3_db
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
